### ISSUE TITLE
unable to find a version of 'chef' to activate...

### ISSUE THREAD

**Issue by drakmail** [applicationsonline/librarian-chef#10]
I'm try to use pushapp (https://github.com/anjlab/pushapp). On step (http://vimeo.com/66528056 , 01:58) with `librarian-chef inst` I has this error:

```
chef|pushapp⚡ ⇒ librarian-chef inst
/Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:100:in `require': unable to find a version of 'chef' to activate (Gem::LoadError)
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.1/lib/librarian/chef/manifest_reader.rb:27:in `compile_manifest'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.1/lib/librarian/chef/manifest_reader.rb:21:in `read_manifest'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.1/lib/librarian/chef/source/local.rb:57:in `fetch_manifest_data'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.1/lib/librarian/chef/source/local.rb:49:in `manifest_data'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.1/lib/librarian/chef/source/local.rb:28:in `fetch_version'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/manifest.rb:117:in `fetch_version!'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/manifest.rb:109:in `fetched_version'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/manifest.rb:55:in `version'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/manifest.rb:93:in `satisfies?'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/dependency.rb:117:in `satisfied_by?'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:107:in `block in check_manifest'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:107:in `each'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:107:in `find'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:107:in `check_manifest'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:57:in `block in recursive_resolve'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:143:in `block (3 levels) in resolving_dependency_map_find_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:176:in `block in scope_checking_manifest'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:175:in `scope_checking_manifest'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:142:in `block (2 levels) in resolving_dependency_map_find_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:196:in `block in map_find'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in `each'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in `map_find'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:141:in `block in resolving_dependency_map_find_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:154:in `block (2 levels) in scope_resolving_dependency'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:168:in `block in scope_checking_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:167:in `scope_checking_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:153:in `block in scope_resolving_dependency'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:152:in `scope_resolving_dependency'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:140:in `resolving_dependency_map_find_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:56:in `recursive_resolve'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:62:in `block in recursive_resolve'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:143:in `block (3 levels) in resolving_dependency_map_find_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:176:in `block in scope_checking_manifest'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:175:in `scope_checking_manifest'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:142:in `block (2 levels) in resolving_dependency_map_find_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:196:in `block in map_find'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in `each'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in `map_find'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:141:in `block in resolving_dependency_map_find_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:154:in `block (2 levels) in scope_resolving_dependency'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:168:in `block in scope_checking_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:167:in `scope_checking_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:153:in `block in scope_resolving_dependency'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:152:in `scope_resolving_dependency'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:140:in `resolving_dependency_map_find_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:56:in `recursive_resolve'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:62:in `block in recursive_resolve'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:143:in `block (3 levels) in resolving_dependency_map_find_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:176:in `block in scope_checking_manifest'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:175:in `scope_checking_manifest'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:142:in `block (2 levels) in resolving_dependency_map_find_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:196:in `block in map_find'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in `each'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in `map_find'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:141:in `block in resolving_dependency_map_find_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:154:in `block (2 levels) in scope_resolving_dependency'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:168:in `block in scope_checking_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:167:in `scope_checking_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:153:in `block in scope_resolving_dependency'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:152:in `scope_resolving_dependency'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:140:in `resolving_dependency_map_find_manifests'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:56:in `recursive_resolve'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:32:in `resolve'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/resolver.rb:16:in `resolve'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/action/resolve.rb:26:in `run'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/cli.rb:169:in `resolve!'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.1/lib/librarian/chef/cli.rb:41:in `install'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/cli.rb:31:in `returning_status'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/cli.rb:26:in `block in bin!'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/cli.rb:47:in `with_environment'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0/lib/librarian/cli.rb:26:in `bin!'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.1/bin/librarian-chef:7:in `<top (required)>'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/bin/librarian-chef:23:in `load'
    from /Users/drakmail/.rbenv/versions/2.0.0-p0/bin/librarian-chef:23:in `<main>'
chef|pushapp⚡ ⇒
```

Before this I install chef and librarian through gem:

```
chef|pushapp⚡ ⇒ gem install chef
Successfully installed chef-11.4.4
Done installing documentation for chef (0 sec).
1 gem installed

chef|pushapp⚡ ⇒ gem install librarian-chef
Fetching: librarian-0.1.0.gem (100%)
Successfully installed librarian-0.1.0
Fetching: librarian-chef-0.0.1.gem (100%)
librarian-chef's executable "librarian-chef" conflicts with librarian
Overwrite the executable? [yN]  y
Successfully installed librarian-chef-0.0.1
Done installing documentation for librarian, librarian-chef (0 sec).
2 gems installed
```

What is wrong?

**Comment by drakmail** [comment]
Found source of problem - chef require json <= 1.7.7, but I has json 1.8.0 installed. after `gem uninstall json -v=1.8.0 && gem install json -v=1.7.7` all works fine!

**Comment by ivanoats** [comment]
but my rails app requires json 1.8.0 .. would love to see this issue fixed.

**Comment by yfeldblum** [comment]
The typical solution is to use some sort of isolated environment for your rails application using either rvm, rbenv, or bundler.

There's not much I can do about a dependency conflict between two external projects (Chef and Rails).
