### ISSUE TITLE
block in tsort_each: topological sort failed: ["windows", "powershell"] (TSort::Cyclic)

### ISSUE THREAD

**Issue by andygrunwald** [applicationsonline/librarian-chef#25]
I get the following error:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:152:in `block in tsort_each': topological sort failed: ["windows", "powershell"] (TSort::Cyclic)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:180:in `each_key'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:135:in `tsort'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:31:in `sort'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/resolver.rb:73:in `sort'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/resolver.rb:19:in `resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/action/resolve.rb:26:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/cli.rb:169:in `resolve!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/cli.rb:41:in `install'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/cli.rb:31:in `returning_status'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in `block in bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/cli.rb:47:in `with_environment'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in `bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/bin/librarian-chef:7:in `<top (required)>'
    from /usr/bin/librarian-chef:23:in `load'
    from /usr/bin/librarian-chef:23:in `<main>'
```

Cheffile:

```
#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Role: base
cookbook 'apt'
cookbook 'build-essential'
cookbook 'git'
cookbook 'vim'

# Role: web
cookbook 'python'
cookbook 'mysql'
cookbook 'php'
cookbook 'composer'

# Role: application
cookbook 'sudo'
cookbook "repositoryhandler",
    :git => "https://github.com/andygrunwald/chef-repositoryhandler",
    :ref => "master"

cookbook "cvsanaly",
    :git => "https://github.com/andygrunwald/chef-cvsanaly",
    :ref => "master"

cookbook "supervisor",
    :git => "https://github.com/poise/supervisor",
    :ref => "master"

cookbook 'rabbitmq'

cookbook "typo3analytics",
    :git => "https://github.com/andygrunwald/chef-typo3analytics",
    :ref => "master"

cookbook "github-linguist",
    :git => "https://github.com/andygrunwald/chef-github-linguist",
    :ref => "master"
```

Ruby: ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]
OS: Mac OSX

**Comment by yfeldblum** [comment]
Closing in favor of applicationsonline/librarian#159, which contains this issue. Thanks!
