### ISSUE TITLE
Issue connecting to Opscode API for Cookbooks

### ISSUE THREAD

**Issue by rsumilang** [applicationsonline/librarian-chef#37]
Librarian-chef has stopped working for connecting to the opscode api (or any) to download any cookbooks. The command `librarian-chef` is now returning the following error when ran:

```
$ librarian-chef install
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:153:in `read_nonblock': Connection reset by peer (Errno::ECONNRESET)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:153:in `rbuf_fill'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1406:in `block in transport_request'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1376:in `request'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:350:in `block (2 levels) in http_get'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:350:in `block in http_get'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:346:in `loop'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:346:in `http_get'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:238:in `cache_remote_object!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:228:in `cache_remote_json!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:173:in `cache_metadata!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:102:in `metadata'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:71:in `version_uris'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:44:in `manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:440:in `manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/dependency.rb:117:in `cache_manifests!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/dependency.rb:113:in `manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in `block in resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in `block (2 levels) in scope_resolving_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in `block in scope_checking_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:178:in `scope_checking_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:164:in `block in scope_resolving_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:163:in `scope_resolving_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:151:in `resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:62:in `recursive_resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:50:in `resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver.rb:23:in `resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:26:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:169:in `resolve!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/cli.rb:41:in `install'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/bin/librarian-chef:7:in `<top (required)>'
    from /usr/bin/librarian-chef:23:in `load'
    from /usr/bin/librarian-chef:23:in `<main>'
```

Any suggestions would be greatly appreciated :)

**Comment by khouse** [comment]
+1 this issue just showed up for us today

[Librarian]   [:github, "\ossec-cookbook", {:ref=>"master"}]
Installing apache2 (1.8.4)
[Librarian] Installing apache2/1.8.4 http://community.opscode.com/api/v1
[Librarian] Caching http://community.opscode.com/api/v1/cookbooks/apache2 to /Users/kyle.house/git/ops/chef-repo/tmp/librarian/cache/source/chef/site/877777683730772c/apache2/metadata.json
[Librarian] Performing http-get for http://community.opscode.com/api/v1/cookbooks/apache2
[Librarian] Responded with redirect to http://community.opscode.com/api/v1/cookbooks/apache2
[Librarian] Performing http-get for https://supermarket.getchef.com/api/v1/cookbooks/apache2
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:153:in `read_nonblock': Connection reset by peer (Errno::ECONNRESET)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:153:in`rbuf_fill'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:144:in`readline'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:28:in`read_new'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1406:in `block in transport_request'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in`catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1376:in`request'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:350:in `block (2 levels) in http_get'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in`start'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:350:in `block in http_get'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:346:in`loop'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:346:in `http_get'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:238:in`cache_remote_object!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:228:in `cache_remote_json!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:173:in`cache_metadata!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:102:in `metadata'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:71:in`version_uris'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:187:in `cache_version!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:109:in`block in to_version_uri'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:378:in `memo'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:108:in`to_version_uri'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:211:in `cache_version_unpacked!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:30:in`install_version!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:434:in `install!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/manifest.rb:97:in`install!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/action/install.rb:49:in `block in install_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/action/install.rb:48:in`each'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/action/install.rb:48:in `install_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/action/install.rb:39:in`perform_installation'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/action/install.rb:12:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/cli.rb:165:in`install!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/lib/librarian/chef/cli.rb:42:in `install'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in`block (2 levels) in bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/cli.rb:31:in `returning_status'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in`block in bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/cli.rb:47:in `with_environment'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in`bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.2/bin/librarian-chef:7:in `<top (required)>'
    from /usr/bin/librarian-chef:23:in`load'
    from /usr/bin/librarian-chef:23:in `<main>'

**Comment by yfeldblum** [comment]
Would upgrading to librarian-chef `v0.0.4` help?

**Comment by khouse** [comment]
Yeah I can't reproduce it on 0.0.4, only on 0.0.2. That works for me, thanks!

**Comment by rsumilang** [comment]
Thanks that worked for me too!

**Comment by rsumilang** [comment]
I'm reopening this issue because librarian-chef is having issues connecting.

```
$ librarian-chef install
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:353:in `block in http_get'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:348:in `loop'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:348:in `http_get'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:238:in `cache_remote_object!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:207:in `cache_version_uri_package!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:216:in `cache_version_uri_unpacked!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:93:in `block in version_uri_manifest'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:381:in `memo'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:92:in `version_uri_manifest'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:88:in `version_manifest'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:54:in `version_dependencies'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:462:in `fetch_dependencies'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/manifest.rb:125:in `fetch_dependencies!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/manifest.rb:117:in `fetched_dependencies'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/manifest.rb:81:in `dependencies'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `block in check_manifest_for_cycles'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `map'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `check_manifest_for_cycles'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:64:in `block in recursive_resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:154:in `block (3 levels) in resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:187:in `block in scope_checking_manifest'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:186:in `scope_checking_manifest'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:153:in `block (2 levels) in resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:211:in `block in map_find'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `map_find'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in `block in resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in `block (2 levels) in scope_resolving_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in `block in scope_checking_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:178:in `scope_checking_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:164:in `block in scope_resolving_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:163:in `scope_resolving_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:151:in `resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:62:in `recursive_resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:70:in `block in recursive_resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:154:in `block (3 levels) in resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:187:in `block in scope_checking_manifest'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:186:in `scope_checking_manifest'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:153:in `block (2 levels) in resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:211:in `block in map_find'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `map_find'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in `block in resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in `block (2 levels) in scope_resolving_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in `block in scope_checking_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:178:in `scope_checking_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:164:in `block in scope_resolving_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:163:in `scope_resolving_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:151:in `resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:62:in `recursive_resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:50:in `resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver.rb:23:in `resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:26:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:169:in `resolve!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/cli.rb:41:in `install'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/bin/librarian-chef:7:in `<top (required)>'
    from /usr/bin/librarian-chef:23:in `load'
    from /usr/bin/librarian-chef:23:in `<main>'
```

**Comment by baltavay** [comment]
I'm seeing the same

**Comment by rsumilang** [comment]
Seems to be working again now but it would be nice if it had a more graceful error that detailed what exactly is failing.

**Comment by dougal** [comment]
This issue is happening for me, today, 2014-10-09.

Happens when using the old community source, the new supermarket resource, and in both procols (http/https).

**Comment by benjaminjackson** [comment]
Same here, just saw this.
