### ISSUE TITLE
SSL error on 0.0.4

### ISSUE THREAD

**Issue by sirupsen** [applicationsonline/librarian-chef#38]
On 0.0.4 I'm getting:

``` text
/Users/sirup/.rubies/ruby-2.1.0/lib/ruby/2.1.0/net/protocol.rb:153:in `read_nonblock': end of file reached (EOFError)
    from /Users/sirup/.rubies/ruby-2.1.0/lib/ruby/2.1.0/net/protocol.rb:153:in `rbuf_fill'
    from /Users/sirup/.rubies/ruby-2.1.0/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
    from /Users/sirup/.rubies/ruby-2.1.0/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
    from /Users/sirup/.rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
    from /Users/sirup/.rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
    from /Users/sirup/.rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'
    from /Users/sirup/.rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
    from /Users/sirup/.rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
    from /Users/sirup/.rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:1378:in `request'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:350:in `block (2 levels) in http_get'
    from /Users/sirup/.rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:853:in `start'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:350:in `block in http_get'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:346:in `loop'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:346:in `http_get'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:238:in `cache_remote_object!'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:228:in `cache_remote_json!'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:173:in `cache_metadata!'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:102:in `metadata'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:71:in `version_uris'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:187:in `cache_version!'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:109:in `block in to_version_uri'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:378:in `memo'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:108:in `to_version_uri'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:211:in `cache_version_unpacked!'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:30:in `install_version!'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb:434:in `install!'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-0.1.2/lib/librarian/manifest.rb:101:in `install!'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-0.1.2/lib/librarian/action/install.rb:49:in `block in install_manifests'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `each'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `install_manifests'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-0.1.2/lib/librarian/action/install.rb:39:in `perform_installation'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-0.1.2/lib/librarian/action/install.rb:12:in `run'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-0.1.2/lib/librarian/cli.rb:165:in `install!'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/lib/librarian/chef/cli.rb:42:in `install'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/gems/librarian-chef-0.0.2/bin/librarian-chef:7:in `<top (required)>'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/bin/librarian-chef:23:in `load'
    from /Users/sirup/code/vagrant/.vagrant/cookbooks/vendor/bundle/bin/librarian-chef:23:in `<main>
```

Works fine on 0.0.3

**Comment by sirupsen** [comment]
This is the list of cookbooks that's causing me problems:

``` text
cookbook 'apache2',         '1.9.6'                                                                                                          
cookbook 'apt',             '2.3.8'                                                                                                          
cookbook 'ark',             '0.6.0'                                                                                                          
cookbook 'build-essential', '1.4.4'                                                                                                          
cookbook 'chef-solo-search','0.5.1'                                                                                                          
cookbook 'database',        '2.0.0'                                                                                                          
cookbook 'gpg',             '0.2.2'                                                                                                          
cookbook 'graphite',        '0.4.3'                                                                                                          
cookbook 'hadoop',          '1.0.9'                                                                                                          
cookbook 'iptables-ng',     '2.2.0'                                                                                                          
cookbook 'java',            '1.22.0'                                                                                                         
cookbook 'jemalloc',        '0.1.1'                                                                                                          
cookbook 'jenkins',         '2.0.2'                                                                                                          
cookbook 'line',            '0.5.1'                                                                                                          
cookbook 'logrotate',       '1.5.0'                                                                                                          
cookbook 'magic_shell',     '1.0.0'                                                                                                          
cookbook 'maven',           '1.1.0'                                                                                                          
cookbook 'nfs',             '0.5.0'                                                                                                          
cookbook 'nodejs',          '1.3.0'                                                                                                          
cookbook 'ntp',             '1.6.0'                                                                                                          
cookbook 'ohai',            '2.0.0'                                                                                                          
cookbook 'openssh',         '1.3.2'                                                                                                          
cookbook 'postfix',         '3.1.4'                                                                                                          
cookbook 'postgresql',      '3.3.4'                                                                                                          
cookbook 'python',          '1.4.6'                                                                                                          
cookbook 'runit',           '1.5.10'                                                                                                         
cookbook 'sudo',            '2.5.2'                                                                                                          
cookbook 'swap',            '0.3.6'                                                                                                          
cookbook 'tmux',            '1.4.0'                                                                                                          
cookbook 'ulimit',          '0.3.2'                                                                                                          
cookbook 'users',           '1.7.0'                                                                                                          
cookbook 'xfs',             '1.1.0' 
```

**Comment by rossmeissl** [comment]
@Sirupsen I had this too until I `gem update librarian-chef` -- it looks like you can close this issue now

**Comment by gordon81** [comment]
sorry do not work

**Comment by vigorIv2** [comment]
@rossmeissl thank you, it helped in my chef instance

**Comment by sirupsen** [comment]
I think this was fixed.
