### ISSUE TITLE
end of file reached (EOFError)

### ISSUE THREAD

**Issue by ghost** [applicationsonline/librarian-chef#39]
Sorry for the issue.

I use librarian-chef with intercity/chef-repo. It doesn't work from the box.

Error message:
/home/com/.rbenv/versions/2.1.0/lib/ruby/2.1.0/net/protocol.rb:153:in `read_nonblock': end of file reached (EOFError)

I tried:
bundle exec librarian-chef clean

bundle exec librarian-chef init

uncomment "cookbook 'chef-client'"

bundle exec librarian-chef install

The same error occurs:

/home/com/.rbenv/versions/2.1.0/lib/ruby/2.1.0/net/protocol.rb:153:in `read_nonblock': end of file reached (EOFError)

Do you know why this happens.

**Comment by sainejob** [comment]
I'm seeing the same...

**Comment by rottmanj** [comment]
What is your default source?  Opscode deprecated their old API and changed the end point to 

```
https://supermarket.getchef.com/api/v1
```

**Comment by sainejob** [comment]
My set-up just stopped working so I was looking to resolve it and starting getting EOFError and ECONNECTRESET.

I was stuck at 0.0.2 and was trying to update to interact with the new API but rubygems dependency API was having problems which I think was my issue.  I have now successfully updated to latest librarian-chef 0.0.4 and back to normal now.

**Comment by perplexes** [comment]
Updated to 0.0.4 and the issue was fixed.

**Comment by diegows** [comment]
0.0.4 fixed it for me too.

**Comment by glaszig** [comment]
0.0.4 fixes it. it is also good advice to update the `site` like @rottmanj  said.

**Comment by michiels** [comment]
Thank you all! I'm updating in intercity/chef-repo.
