### ISSUE TITLE
SSL_connect returned =1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Ope nSSL::SSL::SSLError) ---> Windows

### ISSUE THREAD

**Issue by ddpdevang** [applicationsonline/librarian-chef#47]
C:\Users\Devang\Desktop\chef-rails-dev-box\chef>librarian-chef install
DL is deprecated, please use Fiddle
Installing chef_handler (1.1.6)
C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect returned
=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Ope
nSSL::SSL::SSLError)
        from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:921:in`block in connect'

```
    from C:/Ruby200-x64/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
    from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:921:in `connect'
    from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
    from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:851:in `start'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.3/lib/li
```

brarian/chef/source/site.rb:352:in `block in http_get'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.3/lib/li
brarian/chef/source/site.rb:348:in`loop'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.3/lib/li
brarian/chef/source/site.rb:348:in `http_get'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.3/lib/li
brarian/chef/source/site.rb:238:in`cache_remote_object!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.3/lib/li
brarian/chef/source/site.rb:207:in `cache_version_uri_package!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.3/lib/li
brarian/chef/source/site.rb:216:in`cache_version_uri_unpacked!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.3/lib/li
brarian/chef/source/site.rb:212:in `cache_version_unpacked!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.3/lib/li
brarian/chef/source/site.rb:30:in`install_version!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.3/lib/li
brarian/chef/source/site.rb:436:in `install!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-0.1.2/lib/librari
an/manifest.rb:101:in`install!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-0.1.2/lib/librari
an/action/install.rb:49:in `block in install_manifests'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-0.1.2/lib/librari
an/action/install.rb:48:in`each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-0.1.2/lib/librari
an/action/install.rb:48:in `install_manifests'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-0.1.2/lib/librari
an/action/install.rb:39:in`perform_installation'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-0.1.2/lib/librari
an/action/install.rb:12:in `run'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-0.1.2/lib/librari
an/cli.rb:165:in`install!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.3/lib/li
brarian/chef/cli.rb:42:in `install'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/comman
d.rb:27:in`run'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invoca
tion.rb:126:in `invoke_command'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359
:in`dispatch'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.r
b:440:in `start'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-0.1.2/lib/librari
an/cli.rb:26:in`block (2 levels) in bin!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-0.1.2/lib/librari
an/cli.rb:31:in `returning_status'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-0.1.2/lib/librari
an/cli.rb:26:in`block in bin!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-0.1.2/lib/librari
an/cli.rb:47:in `with_environment'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-0.1.2/lib/librari
an/cli.rb:26:in`bin!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.3/bin/li
brarian-chef:7:in `<top (required)>'
        from C:/Ruby200-x64/bin/librarian-chef:23:in`load'
        from C:/Ruby200-x64/bin/librarian-chef:23:in `<main>'

**Comment by YouSysAdmin** [comment]
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-chef-0.0.3/lib/li brarian/chef/source/site.rb

``` ruby
def http(uri)
  net_http = environment.net_http_class(uri.host).new(uri.host, uri.port)
  net_http.use_ssl = true if uri.scheme == 'https'
  net_http
end
```

replace

``` ruby
def http(uri)
  net_http = environment.net_http_class(uri.host).new(uri.host, uri.port)
  net_http.use_ssl = true if uri.scheme == 'https'
  net_http.verify_mode = OpenSSL::SSL::VERIFY_NONE if net_http.use_ssl?
  net_http
end
```

:)

Variant for realese

``` ruby
def ssl_chek_win(net)
  case RUBY_PLATFORM
    when /win/i, /ming/i
      net.verify_mode = OpenSSL::SSL::VERIFY_NONE if net.use_ssl?
  end
end

def http(uri)
  net_http = environment.net_http_class(uri.host).new(uri.host, uri.port)
  net_http.use_ssl = true if uri.scheme == 'https'
  ssl_chek_win(net_http)
  net_http
end
```

**Comment by whaleyHF** [comment]
Thank you @POStroi 

That resolved the issue for me.

**Comment by YouSysAdmin** [comment]
@whaleyHF 
The long-standing problem :(
Pull request https://github.com/applicationsonline/librarian-chef/pull/49
Automatic windows platform chek  and disable SSL verify.

**Comment by Treeless** [comment]
Still running into this problem. Thanks for the solution @SysAlex

**Comment by citrusoft** [comment]
excellent, how do you know these things?
