### ISSUE TITLE
librarian-chef 0.0.4 fails installing newrelic cookbook

### ISSUE THREAD

**Issue by ajkerr** [applicationsonline/librarian-chef#48]
The latest version of the newrelic cookbook (2.9.0) causes librarian-chef 0.0.4 to fail with the following error:

```
/Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:309:in `unpack_package!': The package archive has too many children! (RuntimeError)
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:224:in `cache_version_uri_unpacked!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:93:in `block in version_uri_manifest'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:381:in `memo'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:92:in `version_uri_manifest'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:88:in `version_manifest'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:54:in `version_dependencies'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:462:in `fetch_dependencies'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/manifest.rb:125:in `fetch_dependencies!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/manifest.rb:117:in `fetched_dependencies'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/manifest.rb:81:in `dependencies'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `block in check_manifest_for_cycles'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `map'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `check_manifest_for_cycles'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:64:in `block in recursive_resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:154:in `block (3 levels) in resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:187:in `block in scope_checking_manifest'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:186:in `scope_checking_manifest'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:153:in `block (2 levels) in resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:211:in `block in map_find'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `map_find'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in `block in resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in `block (2 levels) in scope_resolving_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in `block in scope_checking_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:178:in `scope_checking_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:164:in `block in scope_resolving_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:163:in `scope_resolving_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:151:in `resolving_dependency_map_find_manifests'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:62:in `recursive_resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:50:in `resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/resolver.rb:23:in `resolve'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:26:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:169:in `resolve!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:113:in `update'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/bin/librarian-chef:7:in `<top (required)>'
    from /usr/bin/librarian-chef:23:in `load'
    from /usr/bin/librarian-chef:23:in `<main>'
```

My Cheffile is quite simple:

```
site "https://supermarket.chef.io/api/v1"

cookbook "newrelic", "2.9.0"
```

**Comment by ajkerr** [comment]
Looks like this was an issue with the way the cookbook was published from OS X:  https://github.com/escapestudios-cookbooks/newrelic/issues/162
