### ISSUE TITLE
Period / Dot in Cookbook name raising ambiguous error

### ISSUE THREAD

**Issue by dev-head** [applicationsonline/librarian-chef#52]
I have cookbook with a dot in the name which would not work, after some careful guess work I discovered the issue is with the name of the cookbook. Setting `cookbook 'something.else'` fails, but setting `cookbook 'something_else'` works just fine. 
#### Cheffile

``` ruby
#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'special.snowflake',
    :git => 'https://github.com/martinisoft/chef-rvm'
```

---
#### Cheffile.lock

``` ruby
DEPENDENCIES

```

---
#### librarian-chef install --verbose

``` sh

librarian-chef install --verbose
[Librarian] Ruby Version: 2.0.0
[Librarian] Ruby Platform: universal.x86_64-darwin14
[Librarian] Rubygems Version: 2.0.14
[Librarian] Librarian Version: 0.1.2
[Librarian] Librarian Adapter: chef
[Librarian] Librarian Adapter Version: 0.0.4
[Librarian] Project: /Users/tfoley/ops/so.itc/chef
[Librarian] Specfile: Cheffile
[Librarian] Lockfile: Cheffile.lock
[Librarian] Git: /opt/local/bin/git
[Librarian] Git Version: 2.2.0
[Librarian] Git Environment Variables:
[Librarian]   (empty)
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:site, "https://supermarket.getchef.com/api/v1", {}]
[Librarian]   [:git, "https://github.com/martinisoft/chef-rvm", {}]
[Librarian] Analyzing spec and lock:
[Librarian]   Removed:
[Librarian]   ExplicitRemoved:
[Librarian]   Added:
[Librarian]     special.snowflake
[Librarian]   NonMatchingAdded:
[Librarian]     special.snowflake
[Librarian]   Changed:
[Librarian]   DeepKeep:
[Librarian]   ShallowStrip:
[Librarian] Resolving special.snowflake (>= 0) <https://github.com/martinisoft/chef-rvm#master>
[Librarian]   Checking manifests
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --> origin
[Librarian]     -->   origin/HEAD -> origin/master
[Librarian]     -->   origin/fixsystem
[Librarian]     -->   origin/gh-pages
[Librarian]     -->   origin/master
[Librarian]     -->   origin/new_minitest_suite
[Librarian]     -->   origin/skip-requirements
[Librarian]     --> 4c2590f385d88dd402022b53746eab8acaa00dc5
[Librarian]     --> 4c2590f385d88dd402022b53746eab8acaa00dc5
[Librarian]     Checking special.snowflake/0.10.1 <https://github.com/martinisoft/chef-rvm#master>
[Librarian]       Resolving chef_gem (>= 0.0.0) <(no source specified)>
[Librarian]         Checking manifests
[Librarian] Caching https://supermarket.getchef.com/api/v1/cookbooks/chef_gem to /Users/tfoley/ops/so.itc/chef/tmp/librarian/cache/source/chef/site/2036ece20da2a6e8/chef_gem/metadata.json
[Librarian] Performing http-get for https://supermarket.getchef.com/api/v1/cookbooks/chef_gem
[Librarian] Responded with success
[Librarian]           Checking chef_gem/0.1.0 <https://supermarket.getchef.com/api/v1>
[Librarian]             Resolved chef_gem (>= 0.0.0) <(no source specified)> at chef_gem/0.1.0 <https://supermarket.getchef.com/api/v1>
[Librarian]         Resolved chef_gem (>= 0.0.0) <(no source specified)>
[Librarian]       Resolved special.snowflake (>= 0) <https://github.com/martinisoft/chef-rvm#master> at special.snowflake/0.10.1 <https://github.com/martinisoft/chef-rvm#master>
[Librarian]   Resolved special.snowflake (>= 0) <https://github.com/martinisoft/chef-rvm#master>
[Librarian] Bouncing Cheffile.lock
/Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/lockfile/parser.rb:28:in `parse': Expected DEPENDENCIES topic! (StandardError)
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/lockfile.rb:21:in `load'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/action/persist_resolution_mixin.rb:16:in `persist_resolution'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:169:in `resolve!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/cli.rb:41:in `install'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
    from /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/bin/librarian-chef:7:in `<top (required)>'
    from /usr/bin/librarian-chef:23:in `load'
    from /usr/bin/librarian-chef:23:in `<main>'
rake aborted!
Command failed with status (1): [librarian-chef install --verbose...]
/Users/tfoley/ops/so.itc/chef/Rakefile:138:in `block in <top (required)>'
Tasks: TOP => cookbooks
(See full trace by running task with --trace)
```

**Comment by dwradcliffe** [comment]
Using dots in cookbook names is not supported by chef either. You should change your cookbook names to use underscores instead.
